### ISSUE TITLE
Draw tokenList Layout 

### ISSUE THREAD

**Issue by hogang1223** [orrnrr/orrnrr-ios#2]
## Description
토큰 리스트 레이아웃 그리기

## TODO:
- [x] snapkit 추가
- [x] 기본 사용 컬러 extension 추가
- [ ] 토큰 검색창 추가
- [ ] 토큰 - 보유 - 관심 버튼 추가
- [ ] 토큰 리스트 뷰 추가
- [ ] 버튼 클릭 시 리스트 뷰 변경

## ETC
기타사항
